version: '3'

services:
  boletia_web:
    build:
      context: .
    image: pokeapi_ozon
    container_name: nodejs_container_ozon_pokeapi
    env_file: .env
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules